<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <Btd6ModHelperMSBuildTasksAssembly Condition="'$(Btd6ModHelperMSBuildTasksAssembly)' == '' And Exists('$(MSBuildThisFileDirectory)..\tasks\netstandard2.0\MSBuildTasks.dll')">$(MSBuildThisFileDirectory)..\tasks\netstandard2.0\MSBuildTasks.dll</Btd6ModHelperMSBuildTasksAssembly>
        <Btd6ModHelperMSBuildTasksAssembly Condition="'$(Btd6ModHelperMSBuildTasksAssembly)' == '' And Exists('$(MSBuildThisFileDirectory)MSBuildTasks.csproj')">$(MSBuildThisFileDirectory)bin\$(Configuration)\MSBuildTasks.dll</Btd6ModHelperMSBuildTasksAssembly>
    </PropertyGroup>

    <UsingTask Condition="'$(Btd6ModHelperMSBuildTasksAssembly)' != ''"
               TaskName="ZipEmbeddedResourcesTask"
               AssemblyFile="$(Btd6ModHelperMSBuildTasksAssembly)"/>

    <Target Name="ZipEmbeddedResources"
            BeforeTargets="AssignTargetPaths"
            Condition="'@(ZipEmbeddedResources)' != ''">
        <ItemGroup>
            <EmbeddedResource Remove="@(ZipEmbeddedResources)"/>
        </ItemGroup>

        <ZipEmbeddedResourcesTask SourceFiles="@(ZipEmbeddedResources)"
                                  IntermediateOutputPath="$(IntermediateOutputPath)"
                                  MSBuildProjectDirectory="$(MSBuildProjectDirectory)">
            <Output TaskParameter="OutputFiles" ItemName="_ZippedEmbeddedResource"/>
        </ZipEmbeddedResourcesTask>

        <ItemGroup>
            <EmbeddedResource Include="@(_ZippedEmbeddedResource)"/>
        </ItemGroup>
    </Target>
</Project>
