// <auto-generated> Generated by BloonTagGenerator.cs, do not edit manually </auto-generated>
using System.Collections.Generic;

#pragma warning disable CS1591
namespace BTD_Mod_Helper.Api.Enums;

public static class BloonTag
{
    public const string Bad = "Bad";
    public const string Moabs = "Moabs";
    public const string Fortified = "Fortified";
    public const string Bfb = "Bfb";
    public const string Black = "Black";
    public const string Camo = "Camo";
    public const string Grow = "Grow";
    public const string Boss = "Boss";
    public const string Purple = "Purple";
    public const string Elite = "Elite";
    public const string Blue = "Blue";
    public const string Ceramic = "Ceramic";
    public const string Ddt = "Ddt";
    public const string Frontier = "Frontier";
    public const string Diamondback = "Diamondback";
    public const string DiamondBloon = "DiamondBloon";
    public const string Rock = "Rock";
    public const string DreadRockBloon = "DreadRockBloon";
    public const string AuraBloon = "AuraBloon";
    public const string DoshBloon = "DoshBloon";
    public const string DynamiteBloon = "DynamiteBloon";
    public const string Glass = "Glass";
    public const string GlassBloon = "GlassBloon";
    public const string RetributionBloon = "RetributionBloon";
    public const string RingleaderBloon = "RingleaderBloon";
    public const string Golden = "Golden";
    public const string Green = "Green";
    public const string Lead = "Lead";
    public const string Reanimated = "Reanimated";
    public const string Miniboss = "Miniboss";
    public const string LychSoul = "LychSoul";
    public const string Moab = "Moab";
    public const string Pink = "Pink";
    public const string Rainbow = "Rainbow";
    public const string Red = "Red";
    public const string Test = "Test";
    public const string Tombstone = "Tombstone";
    public const string Zomg = "Zomg";
    public const string White = "White";
    public const string Ice = "Ice";
    public const string Yellow = "Yellow";
    public const string Zebra = "Zebra";
    public const string Regrow = "Grow";

    public static readonly Dictionary<string, string> ByName;
    static BloonTag()
    {
        ByName = new Dictionary<string, string>
        {
            ["Bad"] = Bad,
            ["Moabs"] = Moabs,
            ["Fortified"] = Fortified,
            ["Bfb"] = Bfb,
            ["Black"] = Black,
            ["Camo"] = Camo,
            ["Grow"] = Grow,
            ["Boss"] = Boss,
            ["Purple"] = Purple,
            ["Elite"] = Elite,
            ["Blue"] = Blue,
            ["Ceramic"] = Ceramic,
            ["Ddt"] = Ddt,
            ["Frontier"] = Frontier,
            ["Diamondback"] = Diamondback,
            ["DiamondBloon"] = DiamondBloon,
            ["Rock"] = Rock,
            ["DreadRockBloon"] = DreadRockBloon,
            ["AuraBloon"] = AuraBloon,
            ["DoshBloon"] = DoshBloon,
            ["DynamiteBloon"] = DynamiteBloon,
            ["Glass"] = Glass,
            ["GlassBloon"] = GlassBloon,
            ["RetributionBloon"] = RetributionBloon,
            ["RingleaderBloon"] = RingleaderBloon,
            ["Golden"] = Golden,
            ["Green"] = Green,
            ["Lead"] = Lead,
            ["Reanimated"] = Reanimated,
            ["Miniboss"] = Miniboss,
            ["LychSoul"] = LychSoul,
            ["Moab"] = Moab,
            ["Pink"] = Pink,
            ["Rainbow"] = Rainbow,
            ["Red"] = Red,
            ["Test"] = Test,
            ["Tombstone"] = Tombstone,
            ["Zomg"] = Zomg,
            ["White"] = White,
            ["Ice"] = Ice,
            ["Yellow"] = Yellow,
            ["Zebra"] = Zebra,
            ["Regrow"] = Regrow,
        };
    }
}
