// Generated by GameModeTypeGenerator.cs, do not edit manually
using System.Collections.Generic;

#pragma warning disable CS1591
namespace BTD_Mod_Helper.Api.Enums;

public static class GameModeType
{
    public const string AlternateBloonsRounds = "AlternateBloonsRounds";
    public const string Apopalypse = "Apopalypse";
    public const string Clicks = "Clicks";
    public const string CoopDeflationCash2 = "CoopDeflationCash2";
    public const string CoopDeflationCash3 = "CoopDeflationCash3";
    public const string CoopDeflationCash4 = "CoopDeflationCash4";
    public const string CoopStandardCash2 = "CoopStandardCash2";
    public const string CoopStandardCash3 = "CoopStandardCash3";
    public const string CoopStandardCash4 = "CoopStandardCash4";
    public const string Deflation = "Deflation";
    public const string DoubleMoabHealth = "DoubleMoabHealth";
    public const string Easy = "Easy";
    public const string HalfCash = "HalfCash";
    public const string Hard = "Hard";
    public const string Impoppable = "Impoppable";
    public const string MagicOnly = "MagicOnly";
    public const string Medium = "Medium";
    public const string MilitaryOnly = "MilitaryOnly";
    public const string PrimaryOnly = "PrimaryOnly";
    public const string Reverse = "Reverse";
    public const string Sandbox = "Sandbox";
    public const string Tutorial = "Tutorial";
    public const string BloonsTD6ModHelperDumbMode = "BloonsTD6 Mod Helper-DumbMode";
    public const string None = "";

    public static readonly Dictionary<string, string> ByName;
    static GameModeType()
    {
        ByName = new Dictionary<string, string>
        {
            ["AlternateBloonsRounds"] = AlternateBloonsRounds,
            ["Apopalypse"] = Apopalypse,
            ["Clicks"] = Clicks,
            ["CoopDeflationCash2"] = CoopDeflationCash2,
            ["CoopDeflationCash3"] = CoopDeflationCash3,
            ["CoopDeflationCash4"] = CoopDeflationCash4,
            ["CoopStandardCash2"] = CoopStandardCash2,
            ["CoopStandardCash3"] = CoopStandardCash3,
            ["CoopStandardCash4"] = CoopStandardCash4,
            ["Deflation"] = Deflation,
            ["DoubleMoabHealth"] = DoubleMoabHealth,
            ["Easy"] = Easy,
            ["HalfCash"] = HalfCash,
            ["Hard"] = Hard,
            ["Impoppable"] = Impoppable,
            ["MagicOnly"] = MagicOnly,
            ["Medium"] = Medium,
            ["MilitaryOnly"] = MilitaryOnly,
            ["PrimaryOnly"] = PrimaryOnly,
            ["Reverse"] = Reverse,
            ["Sandbox"] = Sandbox,
            ["Tutorial"] = Tutorial,
            ["BloonsTD6ModHelperDumbMode"] = BloonsTD6ModHelperDumbMode,
            ["None"] = None,
        };
    }
}
