// <auto-generated> Generated by ModHelperSpritesGenerator.cs, do not edit manually </auto-generated>
namespace BTD_Mod_Helper.Api.Enums;

/// <summary>
/// Texture GUIDs for the couple sprites added by ModHelper
/// </summary>
public static class ModHelperSprites
{

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/Btn.png?raw=true">Btn.png</see>
    /// </summary>
    public const string Btn = "Ui[BloonsTD6 Mod Helper-Btn]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnCircle.png?raw=true">BtnCircle.png</see>
    /// </summary>
    public const string BtnCircle = "Ui[BloonsTD6 Mod Helper-BtnCircle]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnCircleHighlight.png?raw=true">BtnCircleHighlight.png</see>
    /// </summary>
    public const string BtnCircleHighlight = "Ui[BloonsTD6 Mod Helper-BtnCircleHighlight]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnHighlight.png?raw=true">BtnHighlight.png</see>
    /// </summary>
    public const string BtnHighlight = "Ui[BloonsTD6 Mod Helper-BtnHighlight]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnLong.png?raw=true">BtnLong.png</see>
    /// </summary>
    public const string BtnLong = "Ui[BloonsTD6 Mod Helper-BtnLong]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnLongHighlight.png?raw=true">BtnLongHighlight.png</see>
    /// </summary>
    public const string BtnLongHighlight = "Ui[BloonsTD6 Mod Helper-BtnLongHighlight]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnRound.png?raw=true">BtnRound.png</see>
    /// </summary>
    public const string BtnRound = "Ui[BloonsTD6 Mod Helper-BtnRound]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnRoundHighlight.png?raw=true">BtnRoundHighlight.png</see>
    /// </summary>
    public const string BtnRoundHighlight = "Ui[BloonsTD6 Mod Helper-BtnRoundHighlight]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnSmall.png?raw=true">BtnSmall.png</see>
    /// </summary>
    public const string BtnSmall = "Ui[BloonsTD6 Mod Helper-BtnSmall]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnSmallHighlight.png?raw=true">BtnSmallHighlight.png</see>
    /// </summary>
    public const string BtnSmallHighlight = "Ui[BloonsTD6 Mod Helper-BtnSmallHighlight]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnSquare.png?raw=true">BtnSquare.png</see>
    /// </summary>
    public const string BtnSquare = "Ui[BloonsTD6 Mod Helper-BtnSquare]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/BtnSquareHighlight.png?raw=true">BtnSquareHighlight.png</see>
    /// </summary>
    public const string BtnSquareHighlight = "Ui[BloonsTD6 Mod Helper-BtnSquareHighlight]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/DownloadBtn.png?raw=true">DownloadBtn.png</see>
    /// </summary>
    public const string DownloadBtn = "Ui[BloonsTD6 Mod Helper-DownloadBtn]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/DownloadBtnLong.png?raw=true">DownloadBtnLong.png</see>
    /// </summary>
    public const string DownloadBtnLong = "Ui[BloonsTD6 Mod Helper-DownloadBtnLong]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/Gradient.png?raw=true">Gradient.png</see>
    /// </summary>
    public const string Gradient = "Ui[BloonsTD6 Mod Helper-Gradient]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/IconMinimal.png?raw=true">IconMinimal.png</see>
    /// </summary>
    public const string IconMinimal = "Ui[BloonsTD6 Mod Helper-IconMinimal]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/Minus.png?raw=true">Minus.png</see>
    /// </summary>
    public const string Minus = "Ui[BloonsTD6 Mod Helper-Minus]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/ModsBtn.png?raw=true">ModsBtn.png</see>
    /// </summary>
    public const string ModsBtn = "Ui[BloonsTD6 Mod Helper-ModsBtn]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/ModSettings.png?raw=true">ModSettings.png</see>
    /// </summary>
    public const string ModSettings = "Ui[BloonsTD6 Mod Helper-ModSettings]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/Plus.png?raw=true">Plus.png</see>
    /// </summary>
    public const string Plus = "Ui[BloonsTD6 Mod Helper-Plus]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/Tick.png?raw=true">Tick.png</see>
    /// </summary>
    public const string Tick = "Ui[BloonsTD6 Mod Helper-Tick]";

    /// <summary>
    /// GUID for image <see href="https://github.com/gurrenm3/BTD-Mod-Helper/blob/master/BloonsTD6%20Mod%20Helper/Resources/Transparency.png?raw=true">Transparency.png</see>
    /// </summary>
    public const string Transparency = "Ui[BloonsTD6 Mod Helper-Transparency]";

}