// <auto-generated> Generated by RoundSetTypeGenerator.cs, do not edit manually </auto-generated>
using System.Collections.Generic;

#pragma warning disable CS1591
namespace BTD_Mod_Helper.Api.Enums;

public static class RoundSetType
{
    public const string Accelerated = "AcceleratedRoundSet";
    public const string Alternate = "AlternateRoundSet";
    public const string BattleCatQuest = "BattleCatQuestRoundSet";
    public const string BouncyDartsTaleStage1 = "BouncyDartsTaleStage1RoundSet";
    public const string BouncyDartsTaleStage2 = "BouncyDartsTaleStage2RoundSet";
    public const string Default = "DefaultRoundSet";
    public const string DefaultSkipEveryOddRound = "DefaultSkipEveryOddRound";
    public const string Endurance = "EnduranceRoundSet";
    public const string FastUpgrades = "FastUpgradesRoundSet";
    public const string FrontierBase1 = "FrontierBase1";
    public const string FrontierBase2 = "FrontierBase2";
    public const string FrontierBase3 = "FrontierBase3";
    public const string FrontierRush1 = "FrontierRush1";
    public const string FrontierRush2 = "FrontierRush2";
    public const string FrontierRush3 = "FrontierRush3";
    public const string FrontierRushFinal = "FrontierRushFinal";
    public const string HeManStage3 = "HeManStage3RoundSet";
    public const string MOABMadness = "MOABMadnessRoundSet";
    public const string QuestAdoraTrial = "QuestAdoraTrialRoundSet";
    public const string QuestBrickellTrial = "QuestBrickellTrialRoundSet";
    public const string QuestChurchillTrial = "QuestChurchillTrialRoundSet";
    public const string QuestCorvusTrial = "QuestCorvusTrialRoundSet";
    public const string QuestEtienneTrial = "QuestEtienneTrialRoundSet";
    public const string QuestEziliTrial = "QuestEziliTrialRoundSet";
    public const string QuestGeraldoTrial = "QuestGeraldoTrialRoundSet";
    public const string QuestGwendolinTrial = "QuestGwendolinTrialRoundSet";
    public const string QuestMermonkeyStage1 = "QuestMermonkeyStage1RoundSet";
    public const string QuestObynTrial = "QuestObynTrialRoundSet";
    public const string QuestPatTrial = "QuestPatTrialRoundSet";
    public const string QuestPsiTrial = "QuestPsiTrialRoundSet";
    public const string QuestQuincyTrial = "QuestQuincyTrialRoundSet";
    public const string QuestRosaliaTrial = "QuestRosaliaTrialRoundSet";
    public const string QuestSaudaTrial = "QuestSaudaTrialRoundSet";
    public const string QuestSilasTrial = "QuestSilasTrialRoundSet";
    public const string QuestStrikerTrial = "QuestStrikerTrialRoundSet";
    public const string RogueBloonierSet = "RogueBloonierSet";
    public const string RogueDenseSet = "RogueDenseSet";
    public const string RogueImmuneSet = "RogueImmuneSet";
    public const string RogueLeadSet = "RogueLeadSet";
    public const string RoguePinkSet = "RoguePinkSet";
    public const string RoguePurpleSet = "RoguePurpleSet";
    public const string Rogue = "RogueRoundSet";
    public const string ScoopsTaleIPart1 = "ScoopsTaleIPart1RoundSet";
    public const string ScoopsTaleIPart2 = "ScoopsTaleIPart2RoundSet";
    public const string ScoopsTaleIPart3 = "ScoopsTaleIPart3RoundSet";
    public const string SkeletorQuest1 = "SkeletorQuestRoundSet1";
    public const string ABR = "AlternateRoundSet";
    public const string Empty = "";

    public static readonly Dictionary<string, string> ByName;
    static RoundSetType()
    {
        ByName = new Dictionary<string, string>
        {
            ["Accelerated"] = Accelerated,
            ["Alternate"] = Alternate,
            ["BattleCatQuest"] = BattleCatQuest,
            ["BouncyDartsTaleStage1"] = BouncyDartsTaleStage1,
            ["BouncyDartsTaleStage2"] = BouncyDartsTaleStage2,
            ["Default"] = Default,
            ["DefaultSkipEveryOddRound"] = DefaultSkipEveryOddRound,
            ["Endurance"] = Endurance,
            ["FastUpgrades"] = FastUpgrades,
            ["FrontierBase1"] = FrontierBase1,
            ["FrontierBase2"] = FrontierBase2,
            ["FrontierBase3"] = FrontierBase3,
            ["FrontierRush1"] = FrontierRush1,
            ["FrontierRush2"] = FrontierRush2,
            ["FrontierRush3"] = FrontierRush3,
            ["FrontierRushFinal"] = FrontierRushFinal,
            ["HeManStage3"] = HeManStage3,
            ["MOABMadness"] = MOABMadness,
            ["QuestAdoraTrial"] = QuestAdoraTrial,
            ["QuestBrickellTrial"] = QuestBrickellTrial,
            ["QuestChurchillTrial"] = QuestChurchillTrial,
            ["QuestCorvusTrial"] = QuestCorvusTrial,
            ["QuestEtienneTrial"] = QuestEtienneTrial,
            ["QuestEziliTrial"] = QuestEziliTrial,
            ["QuestGeraldoTrial"] = QuestGeraldoTrial,
            ["QuestGwendolinTrial"] = QuestGwendolinTrial,
            ["QuestMermonkeyStage1"] = QuestMermonkeyStage1,
            ["QuestObynTrial"] = QuestObynTrial,
            ["QuestPatTrial"] = QuestPatTrial,
            ["QuestPsiTrial"] = QuestPsiTrial,
            ["QuestQuincyTrial"] = QuestQuincyTrial,
            ["QuestRosaliaTrial"] = QuestRosaliaTrial,
            ["QuestSaudaTrial"] = QuestSaudaTrial,
            ["QuestSilasTrial"] = QuestSilasTrial,
            ["QuestStrikerTrial"] = QuestStrikerTrial,
            ["RogueBloonierSet"] = RogueBloonierSet,
            ["RogueDenseSet"] = RogueDenseSet,
            ["RogueImmuneSet"] = RogueImmuneSet,
            ["RogueLeadSet"] = RogueLeadSet,
            ["RoguePinkSet"] = RoguePinkSet,
            ["RoguePurpleSet"] = RoguePurpleSet,
            ["Rogue"] = Rogue,
            ["ScoopsTaleIPart1"] = ScoopsTaleIPart1,
            ["ScoopsTaleIPart2"] = ScoopsTaleIPart2,
            ["ScoopsTaleIPart3"] = ScoopsTaleIPart3,
            ["SkeletorQuest1"] = SkeletorQuest1,
            ["ABR"] = ABR,
            ["Empty"] = Empty,
        };
    }
}
