export enum Language {
  Arabic = "ar",
  Danish = "da",
  Dutch = "nl",
  English = "en",
  Finnish = "fi",
  French = "fr",
  German = "de",
  Italian = "it",
  Japanese = "ja",
  Korean = "ko",
  Norwegian = "no",
  Polish = "pl",
  Portuguese_Brazil = "pt-BR",
  Russian = "ru",
  SimplifiedChinese = "zh-CN",
  Spanish_LATAM = "es-419",
  Spanish_Spain = "es",
  Swedish = "sv",
  Thai = "th",
  TraditionalChinese = "zh-TW",
  Turkish = "tr",
}
