using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using BTD_Mod_Helper.Api.Commands;

namespace BTD_Mod_Helper.Api;

/// <summary>
/// ModContent class for code/data generators that write files into a mod project's source code.
/// per output.
/// </summary>
public abstract class ModSourceFileGenerator : ModContent
{
    /// <summary>
    /// Root Namespace for the class to be in before <see cref="OutputPath"/>
    /// </summary>
    public virtual string RootNamespace => field ??= mod.MelonAssembly.Assembly.GetValidTypes()
        .Where(type => type.Namespace != null)
        .Select(type => type.Namespace!.Split(".").First())
        .GroupBy(ns => ns)
        .OrderByDescending(grp => grp.Count())
        .Select(grp => grp.Key)
        .First();

    /// <summary>
    /// Folder segments under the root project that the generated file lives in.
    /// </summary>
    public abstract string[] OutputPath { get; }

    /// <summary>
    /// C# class name of the generated file (and its base filename).
    /// </summary>
    public virtual string FileName => Name.Replace("Generator", "");

    /// <summary>
    /// File extension to use
    /// </summary>
    public virtual string FileExt => "cs";

    /// <summary>
    /// C# namespace of the generated file.
    /// </summary>
    public virtual string Namespace =>
        OutputPath.Length == 0 ? RootNamespace : $"{RootNamespace}.{string.Join('.', OutputPath)}";

    /// <summary>
    /// <c>&lt;ModHelperSourceFolder&gt;/BloonsTD6 Mod Helper</c> — root for everything generators emit.
    /// </summary>
    public virtual string RootFolder =>
        Path.Combine(mod is MelonMain ? MelonMain.ModHelperSourceFolder : MelonMain.ModSourcesFolder, mod.GetModName());

    /// <summary>
    /// Multiple classes to generate, if applicable
    /// </summary>
    public virtual IEnumerable<string> FileNames => [FileName];

    /// <summary>
    /// Comment to include at the top of the file about it being a generated file
    /// </summary>
    public virtual string GeneratedComment => $"Generated by {GetType().Name}.cs, do not edit manually";

    /// <inheritdoc />
    public override void Register()
    {
        mod.AddContent(new Cmd(this));
    }

    /// <summary>
    /// Append the file's contents to <paramref name="sb"/> for the class
    /// </summary>
    public virtual void Generate(StringBuilder sb, ref string fileName) => Generate(sb);

    /// <summary>
    /// Append the file's contents to <paramref name="sb"/>
    /// </summary>
    public virtual void Generate(StringBuilder sb) => throw new NotImplementedException();

    /// <summary>
    /// Build the file contents into a fresh <see cref="StringBuilder"/> and write them to <see cref="OutputPath"/>/<see cref="FileName"/>.<see cref="FileExt"/>.
    /// </summary>
    public virtual void Generate()
    {
        foreach (var className in FileNames)
        {
            var sb = new StringBuilder();
            var name = className;

            if (!string.IsNullOrWhiteSpace(GeneratedComment))
            {
                sb.Append(FileExt switch
                {
                    "cs" => $"// <auto-generated> {GeneratedComment} </auto-generated>\n",
                    "md" => $"<!--{GeneratedComment}-->\n",
                    _ => ""
                });
            }

            Generate(sb, ref name);

            var path = Path.Combine([RootFolder, ..OutputPath, name + "." + FileExt]);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, sb.ToString());

            mod.LoggerInstance.Msg($"Generated {path}");
        }
    }

    private class Cmd(ModSourceFileGenerator generator) : ModCommand<GenerateCommand>
    {
        public override string Command => generator.FileName;
        public override string Help => $"Generates using {generator.Name}";

        public override bool Execute(ref string resultText)
        {
            generator.Generate();
            return true;
        }
    }
}