using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BTD_Mod_Helper.SourceGenerators;

/// <summary>
/// Generates a file ModResources.g.cs filled with strongly typed entries for different embedded content within the mod.
/// Can opt out by setting csproj property GenerateModResources to false
/// </summary>
[Generator(LanguageNames.CSharp)]
public class ModResourcesGenerator : IIncrementalGenerator
{
    private const string BloonsModFullName = "global::BTD_Mod_Helper.BloonsMod";
    private const string ResourceTypeNamespace = "global::BTD_Mod_Helper.Api.Data";

    private static readonly Dictionary<string, string> ExtensionToType = new(StringComparer.OrdinalIgnoreCase)
    {
        [".png"] = "SpriteResource",
        [".jpg"] = "SpriteResource",
        [".wav"] = "AudioClipResource",
        [".mp3"] = "AudioClipResource",
        [".ogg"] = "AudioClipResource",
        [".flac"] = "AudioClipResource",
        [".aac"] = "AudioClipResource",
        [".wma"] = "AudioClipResource",
        [".m4a"] = "AudioClipResource",
        [".bundle"] = "BundleResource",
        [".json"] = "JsonResource",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var buildContext = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
            options.GlobalOptions.TryGetValue("build_property.ProjectDir", out var dir);
            options.GlobalOptions.TryGetValue("build_property.GenerateModResources", out var enabled);
            return (
                Enabled: !string.Equals(enabled, "false", StringComparison.OrdinalIgnoreCase),
                RootNamespace: string.IsNullOrWhiteSpace(ns) ? "GeneratedResources" : ns!,
                ProjectDir: dir ?? ""
            );
        });

        var modType = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax {BaseList: not null},
                transform: static (ctx, ct) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax) ctx.Node, ct)
                        is not {IsAbstract: false} symbol) return null;
                    for (var bt = symbol.BaseType; bt is not null; bt = bt.BaseType)
                    {
                        if (bt.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == BloonsModFullName)
                            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    }
                    return null;
                })
            .Where(static s => s != null)
            .Collect()
            .Select(static (arr, _) => arr.IsDefaultOrEmpty ? null : arr[0]);

        var resources = context.AdditionalTextsProvider
            .Select((text, _) =>
            {
                if (!ExtensionToType.ContainsKey(Path.GetExtension(text.Path))) return default;
                var name = Path.GetFileNameWithoutExtension(text.Path);
                return string.IsNullOrWhiteSpace(name) ? default : (Name: name, Path: text.Path);
            })
            .Where(r => r.Name != null)
            .Collect();

        context.RegisterSourceOutput(buildContext.Combine(modType, resources), (ctx, data) =>
        {
            var (build, modFullName, entries) = data;
            if (!build.Enabled) return;
            if (string.IsNullOrEmpty(modFullName)) return;

            var distinct = entries.IsDefaultOrEmpty ? [] : entries.Distinct().ToList();

            var emitted = new List<(string Field, string ResourceName, string Path)>();
            foreach (var group in distinct.GroupBy(r => r.Name, StringComparer.Ordinal))
            {
                var items = group.ToList();
                var disambiguate = items.Count > 1;
                foreach (var r in items)
                {
                    var raw = disambiguate ? r.Name + "_" + Path.GetExtension(r.Path).TrimStart('.') : r.Name;
                    emitted.Add((MakeIdentifier(raw), r.Name, r.Path));
                }
            }
            emitted.Sort((a, b) => string.Compare(a.Field, b.Field, StringComparison.Ordinal));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"namespace {build.RootNamespace};");
            sb.AppendLine();
            sb.AppendLine("internal static partial class ModResources");
            sb.AppendLine("{");

            var seen = new HashSet<string>(StringComparer.Ordinal);

            foreach (var (field, resourceName, fullPath) in emitted)
            {
                var relative = GetRelativePath(fullPath, build.ProjectDir);
                var typeName = ExtensionToType[Path.GetExtension(fullPath)];
                EmitField(
                    Unique(field),
                    $"<c>{SecurityElement.Escape(relative)}</c>",
                    $"{ResourceTypeNamespace}.{typeName}<{modFullName}>",
                    $"\"{resourceName}\"");
            }

            var audio = new List<(string Field, string Path, string BaseName, int Number)>();
            var standaloneAudioNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var e in emitted)
            {
                if (ExtensionToType[Path.GetExtension(e.Path)] != "AudioClipResource") continue;

                var parsed = ParseTrailingDigits(e.ResourceName);
                if (parsed.Number.HasValue)
                    audio.Add((e.Field, e.Path, parsed.BaseName, Number: parsed.Number.Value));
                else
                    standaloneAudioNames.Add(e.ResourceName);
            }

            var randomGroups = audio
                .GroupBy(t => t.BaseName, StringComparer.Ordinal)
                .Where(g => g.Count() >= 2 && !standaloneAudioNames.Contains(g.Key))
                .OrderBy(g => g.Key, StringComparer.Ordinal);

            foreach (var group in randomGroups)
            {
                var variants = group.OrderBy(t => t.Number).ToList();
                var args = string.Join(", ", variants.Select(v => v.Field));
                var paths = string.Join(", ", variants.Select(v =>
                    SecurityElement.Escape(GetRelativePath(v.Path, build.ProjectDir))));
                EmitField(
                    Unique(MakeIdentifier(group.Key)),
                    $"Randomized from <c>{paths}</c>",
                    $"{ResourceTypeNamespace}.RandomizedAudioClipResource<{modFullName}>",
                    $"\"{group.Key}\", {args}");
            }

            sb.AppendLine("}");
            ctx.AddSource("ModResources.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            return;

            void EmitField(string field, string docInner, string typeExpr, string ctorArgs)
            {
                sb.AppendLine($"    /// <summary> {docInner} </summary>");
                sb.AppendLine($"    internal static readonly {typeExpr} {field} = new({ctorArgs});");
            }

            string Unique(string baseField)
            {
                var u = baseField;
                var n = 2;
                while (!seen.Add(u)) u = baseField + "_" + n++;
                return u;
            }

            (string BaseName, int? Number) ParseTrailingDigits(string s)
            {
                var i = s.Length;
                while (i > 0 && char.IsDigit(s[i - 1])) i--;
                return i == 0 || i == s.Length || !int.TryParse(s.Substring(i), out var n)
                    ? (s, null)
                    : (s.Substring(0, i), n);
            }
        });
    }

    private static string GetRelativePath(string path, string projectDir)
    {
        if (!Path.IsPathRooted(path)) return path.Replace('\\', '/');
        if (string.IsNullOrEmpty(projectDir)) return Path.GetFileName(path);

        var prefix = projectDir.TrimEnd('/', '\\') + Path.DirectorySeparatorChar;
        return path.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)
            ? path.Substring(prefix.Length).Replace('\\', '/')
            : Path.GetFileName(path);
    }

    private static string MakeIdentifier(string raw)
    {
        var sb = new StringBuilder(raw.Length);
        for (var i = 0; i < raw.Length; i++)
        {
            var c = raw[i];
            var ok = i == 0 ? SyntaxFacts.IsIdentifierStartCharacter(c) : SyntaxFacts.IsIdentifierPartCharacter(c);
            sb.Append(ok ? c : '_');
        }
        if (sb.Length == 0) sb.Append('_');
        return sb.ToString();
    }
}